main/__init__.py
# ./main/__init__.py

from flask import Blueprint

bp = Blueprint("main",__name__)

from .routes import *
from .datamodel import init_app as _init_app

def init_app(app):
    _init_app(app)

main/routes.py
# ./main/routes.py

from flask import render_template, request
from flask_login import login_required

from . import bp
from .datamodel import BEP
from auth import Permission

@bp.route("/")
def index():
    return render_template("index.html", title = "Home")


@bp.route("/bep_calc")
def bep_calc():
    return render_template("bep.html", title="BEP-Rechner")


@bp.route("/history")
@login_required
def history():
    bep_list = BEP.get_all()
    return render_template("history.html", title="BEP-History")

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{url_for('static', filename='css/styles.css')}}">

    <title>{{title}} - Break-Even-Point-Rechner</title>
</head>

<body>
    <nav>
        <ul>
            <a href="{{url_for('main.index')}}">
                <li>Home</li>
            </a>
            <a href="{{url_for('main.bep_calc')}}">
                <li>BEP-Rechner</li>
            </a>
            <div class="nav-r">
                {% if current_user.is_admin %}
                <a href="{{url_for('auth.users')}}">
                    <li>Userlist</li>
                </a>
                {% endif %}
                {% if current_user.is_authenticated %}
                <li class="dropbtn">Angemeldet als: {{ current_user.name }}
                    <ul>
                        <a href="{{url_for('auth.profile')}}">
                            <li>Profil</li>
                        </a>
                        <a href="{{url_for('main.history')}}">
                            <li>Verlauf</li>
                        </a>
                        <a href="{{url_for('auth.logout')}}" id="signout">
                            <li>Abmelden</li>
                        </a>
                    </ul>
                </li>
                {% else %}
                <a href="{{url_for('auth.login')}}"><li>Login</li></a>
                {% endif %}
            </div>
        </ul>
    </nav>

    <main>
        {% block messages %}
        <div id="messages">
            {% for type,message in get_flashed_messages(with_categories=True) %}
            <div class="flash-{{type}}">
                <div class="flash_icon_container">
                    <span class="flash_icon-{{type}}"></span>
                </div>
                <div class="flash_message">{{ message }}</div>
                <div class="flash_close"><svg xmlns="http://www.w3.org/2000/svg" width="20" viewBox="0 0 20 20"
                        height="20">
                        <path fill="#393a37"
                            d="m15.8333 5.34166-1.175-1.175-4.6583 4.65834-4.65833-4.65834-1.175 1.175 4.65833 4.65834-4.65833 4.6583 1.175 1.175 4.65833-4.6583 4.6583 4.6583 1.175-1.175-4.6583-4.6583z">
                        </path>
                    </svg></div>
            </div>
            {% endfor %}
        </div>



        {% endblock %}

        {% block content %}
        {% endblock %}
    </main>

    <script src="{{url_for('static', filename='js/bep.js')}}">
    </script>

</body>

</html>

templates/bep.html
{% extends "base.html" %}

{% block content %}
<header class="bep-header">
    <h1> Break-Even-Point Rechner</h1>
</header>
<div class="bep-settings">
    <form action="#" method="POST" class="bep-form">
        <input type="submit" class="submit" name="submit" id="save" value="Szenario speichern">
        <span id="bep-controls">
            <div class="bep-control-group">
                <label for="fixkosten" class="label">Fixkosten</label>
                <input type="range" id="s_fixkosten" name="s_fixkosten" min="0" max="" value="">
                <input type="number" id="fixkosten" name="fixkosten" value="">
            </div>
            <div class="bep-control-group">
                <label for="varkosten" class="label">Variable Kosten pro Stück</label>
                <input type="range" id="s_varkosten" name="_varkosten" min="0" max="" value="">
                <input type="number" id="varkosten" name="varkosten" value="">
            </div>
            <div class="bep-control-group">
                <label for="preis" class="label">Preis pro Stück</label>
                <input type="range" id="s_preis" name="s_preis" min="0" max="" value="">
                <input type="number" id="preis" name="preis" value="">
            </div>
        </span>
    </form>
</div>
<div class="bep-graph">

</div>

{% endblock %}

templates/change_email.html
{% extends "base.html" %}

{% block content %}
<br><br>

<form class="form" method="POST" action="#">
    <h2>Email-Adresse ändern</h2>
    <span class="input-span">
        <label for="email" class="label">Neue Email</label>
        <input type="email" name="email" id="email" autofocus title="Neue Email-Adresse eingeben." required
            oninvalid="this.setCustomValidity('Bitte geben Sie eine Email-Adresse ein.')"
            oninput="this.setCustomValidity('')" />
    </span>
    <span class="input-span">
        <label for="password" class="label">Password zur Kontrolle</label>
        <input type="password" name="password" id="password" title="Passwort zur Kontrolle eingeben." required
            oninvalid="this.setCustomValidity('Bitte geben Sie ihr Passwort ein.')"
            oninput="this.setCustomValidity('')" />
    </span>
    <br>
    <button class="submit" id="confirm" name="submit" value="save">Neue Email-Adresse speichern</button>
    <button class="cancel" id="cancel" name="submit" value="cancel" formnovalidate>Abbruch</button>
</form>

{% endblock %}

templates/change_password.html
{% extends "base.html"%}
{% block content %}
<br><br>

<form action="#" method="POST" class="form" id="change-password-form">
    <span class="input-span">
        <label for="old_password" class="label">Altes Passwort:</label>
        <input id="old_password" name="old_password" value="" type="password" title="Geben Sie ihr altes Passwort ein."
            required oninvalid="this.setCustomValidity('Bitte geben Sie ihr altes Passwort ein.')"
            oninput="this.setCustomValidity('')" autofocus />
    </span>
    <span class="input-span">
        <label for="new_password" class="label">Neues Passwort:</label>
        <input id="new_password" name="new_password" value="" type="password"
            title="Geben Sie ein neues Passwort mit mindestens {{ min_length }} Zeichen ein." required
            oninvalid="this.setCustomValidity('Bitte geben Sie ein neues Passwort mit mindestens {{ min_length }} Zeichen ein.')"
            oninput="this.setCustomValidity('')" />
    </span>
    <span class="input-span">
        <label for="confirm_password" class="label">Password Wiederholung:</label>
        <input id="confirm_password" name="confirm_password" value="" type="password"
            title="Wiederholen Sie ihr neues Passwort zur Kontrolle." required
            oninvalid="this.setCustomValidity('Die Passwörter stimmen nicht überein.')"
            oninput="this.setCustomValidity('')" />
    </span>
    <button class="submit" id="confirm" name="submit" value="submit">Neues Password speichern</button>
    <button class="cancel" id="cancel" name="submit" value="cancel" formnovalidate>Abbruch</button>
</form>
{% endblock %}

templates/change_username.html
{% extends "base.html" %}

{% block content %}
<br><br>

<form class="form" method="POST" action="#">
  <h2>Benutzername ändern</h2>
  <span class="input-span">
    <label for="username" class="label">Neuer Benutzername</label>
    <input type="text" name="username" id="username" autofocus title="Neuen Benutzername eingeben." required
      oninvalid="this.setCustomValidity('Bitte geben Sie einen Benutzernamen ein.')"
      oninput="this.setCustomValidity('')" />
  </span>
  <span class="input-span">
    <label for="password" class="label">Password zur Kontrolle</label>
    <input type="password" name="password" id="password" title="Passwort zur Kontrolle eingeben." required
      oninvalid="this.setCustomValidity('Bitte geben Sie ihr Passwort ein.')" oninput="this.setCustomValidity('')" />
  </span>
  <br>
  <button class="submit" id="confirm" name="submit" value="save">Neuen Benutzername speichern</button>
  <button class="cancel" id="cancel" name="submit" value="cancel" formnovalidate>Abbruch</button>
</form>


{% endblock %}

templates/history.html
{% extends "base.html" %}

{% block content %}

{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

templates/login.html
{% extends "base.html" %}
{% block content %}
<br><br>

<form class="form" method="POST" action="#">
  <h2>Login</h2>
  <span class="input-span">
    <label for="username" class="label">Email or Username</label>
    <input type="text" name="username" id="username" autofocus required
      oninvalid="this.setCustomValidity('Bitte geben Sie Ihre Email-Adresse oder Ihren Benutzername ein.')"
      oninput="this.setCustomValidity('')" />
  </span>
  <span class="input-span">
    <label for="password" class="label">Password</label>
    <input type="password" name="password" id="password" required
      oninvalid="this.setCustomValidity('Bitte geben Sie ihr Passwort ein.')" oninput="this.setCustomValidity('')" />
  </span>
  <br>
  <input class="submit" type="submit" value="Login" name="submit" />
  <span class="span">Don't have an account? <a href="{{url_for('auth.register')}}">Sign up</a></span>
</form>
{% endblock %}

templates/profile.html
{% extends "base.html" %}

{% block content %}
<br><br>

  <div class="settings-container">
    <h2>Account Settings</h2>

    <div class="setting-item" id="username-section">
      <label>Username</label>
      <span class="value" id="username-display">{{user.name}}</span>
      <button class="edit-btn" onclick="location.href=`{{url_for('auth.change_username')}}`">Edit</button>
    </div>

    <div class="setting-item" id="email-section">
      <label>Email</label>
      <span class="value" id="email-display">{{user.email}}</span>
      <button class="edit-btn" onclick="location.href=`{{url_for('auth.change_email')}}`">Edit</button>
    </div>

    <div class="setting-item" id="password-section">
      <label>Password</label>
      <span class="value" id="password-display">••••••••</span>
      <button class="edit-btn" onclick="location.href=`{{url_for('auth.change_password')}}`">Edit</button>
    </div>
  </div>





{% endblock %}

templates/register.html
{% extends "base.html" %}
{% block content %}
<br><br>

<form class="form" method="POST" action="#">
    <h2>Sign up</h2>
    <span class="input-span">
        <label for="username" class="label"> Username</label>
        <input type="text" name="username" id="username" autofocus required
            oninvalid="this.setCustomValidity('Bitte geben Sie einen Benutzernamen ein.')"
            oninput="this.setCustomValidity('')" />
    </span>
    <span class="input-span">
        <label for="email" class="label">Email </label>
        <input type="email" name="email" id="email" required
            oninvalid="this.setCustomValidity('Bitte geben Sie eine Email-Adresse ein.')"
            oninput="this.setCustomValidity('')" />
    </span>
    <span class="input-span">
        <label for="password" class="label">Password</label>
        <input type="password" name="password" id="password" required
            oninvalid="this.setCustomValidity('Bitte geben Sie ihr Passwort ein.')"
            oninput="this.setCustomValidity('')" />
    </span>
    <br>
    <input class="submit" type="submit" value="Register" name="submit" />
    <span class="span">Already have an account? <a href="{{url_for('auth.login')}}">Login</a></span>
</form>
{% endblock %}

templates/user.html
{% extends "base.html"%}
{% block content %}
<br><br>

<form class="form" action="#" method="POST">
    {% if user %}
    <h2>Edit User: {{user.id}}</h2>
    {% else %}
    <h2>Neuen Benutzer hinzufügen</h2>
    {% endif %}
    <span class="input-span">
        <label for="username" class="label">Name</label>
        <input class="input" type="text" id="username" name="name" value="{% if user %}{{ user.name }}{% endif %}"
            placeholder="" title="Geben Sie einen Benutzernamen ein. Dieser muss eindeutig sein." autofocus required
            oninvalid="this.setCustomValidity('Bitte geben Sie einen Benutzernamen ein.')" oninput="this.setCustomValidity('')" />
    </span>
    <span class="input-span">
        <label for="email" class="label">Email</label>
        <input class="input" id="email" name="email" value="{% if user %}{{ user.email }}{% endif %}" type="email"
            placeholder="" title="Geben Sie die email des Nutzers ein. Diese muss eindeutig sein." required
            oninvalid="this.setCustomValidity('Bitte geben Sie eine Email ein.')" oninput="this.setCustomValidity('')" />
    </span>
    <span class="input-span">
        <label for="role" class="label">Benutzerrolle</label>
        <div class="custom-select">
            <select class="input" id="role" name="role">
                {% for r in roles %}
                <option value="{{r.name}}" {% if user %} {% if r.name==user.role.name %}selected{% endif %} {% else %}
                    {% if r.default==True %}selected{% endif %} {% endif %}>
                    {{r.name}}</option>
                {% endfor %}
            </select>
        </div>
    </span>
    <button id="confirm" name="submit" value="save" class="submit">
        {%if user %}
        Änderungen speichern
        {% else %}
        Benutzer hinzufügen
        {% endif %}
    </button>
    <button id="cancel" name="submit" value="cancel" class="cancel" formnovalidate>Abbruch</button>
</form>
{% endblock %}

templates/userlist.html
{% extends "base.html" %}

{% block content %}
<table>
    <div id="buttons_users">
        <button type="button" id="btn_new" class="btn_users" onclick="location.href=`{{url_for('auth.add_user')}}`;"></button>
        <button type="button" id="btn_refresh" class="btn_users" onclick="location.href=`{{url_for('auth.users')}}`;"></button>
    </div>
    <thead>
        <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Rolle</th>
            <th id="ak">Aktionen</th>
        </tr>
    </thead>
    <tbody>
        {% for u in users %}
        <tr>
            <td>{{u.name}}</td>
            <td>{{u.email}}</td>
            <td>{{u.role.name}}</td>
            <td>
                <a href="{{url_for('auth.edit_user', id=u.id)}}" id="btnedit" class="btnedit" title="bearbeiten"></a>
                <a href="{{url_for('auth.delete_user', id=u.id)}}" 
                   id="btndelete" 
                   class="button danger" 
                   title="löschen"
                   data-message="Wollen Sie den Nutzer {{u.name}} wirklich löschen?">
                </a>
                <a href="{{url_for('auth.reset_password', id=u.id)}}"
                   class="button danger"
                   title="Passwort zurücksetzen"
                   id = "btn_reset"
                   data-message="Wollen Sie das Passwort für {{u.name}} wirklich zurücksetzen?"
                   ></a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}